name: Update LeetWar Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # ШАГ 1: Запускаем наш калькулятор опыта для таблицы
      - name: Run XP calculator
        run: python update_stats.py

      # ШАГ 2: Генерируем красивую карточку для mrfakek
      - name: Generate Card for mrfakek
        uses: joshcai/leetcode-stats-action@v2
        with:
          username: mrfakek
          theme: dark

      # ШАГ 3: Генерируем красивую карточку для TrueRyoB
      - name: Generate Card for TrueRyoB
        uses: joshcai/leetcode-stats-action@v2
        with:
          username: TrueRyoB
          theme: dark
          # Перенаправляем вторую карточку в её личные маркеры
          start_marker: "<!-- leetcode_friend:start -->"
          end_marker: "<!-- leetcode_friend:end -->"

      # ШАГ 4: Сохраняем всё вместе в README.md
      - name: Commit and Push changes
        run: |
          git config --global user.name "LeetWarBot"
          git config --global user.email "bot@leetwar.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "⚔️ Робот обновил таблицу PvP, XP и карточки" && git push)
